
walk:
  # Path to URDF
  model_file: "./urdf/harpy_planar.urdf"

  # configuration space
  # z-pos, x-pos, [0-1]
  # theta,        [2]
  # hip_r, knee_r, ankle_r, foot_r [3-6]
  # hip_l, knee_l, ankle_l, foot_l [7-10]

  # MPC parameters
  T: 10.0   # total time horizon
  dt: 0.05 # time step

  # Cost Parameters
  w_4bar_q: 100
  w_4bar_v: 10
  Wq:   [70, 60, 1, 5, 5, 5, 5, 5, 5, 5, 5]
  Wv:   [700, 100, 1, 10, 10, 10, 10, 10, 10, 10, 10]
  R:    [100_000, 100_000, 100_000, 0.01, 0.01, 0, 0.01, 0.01, 0.01, 0, 0.01]
  Wf_q: [60, 60, 1, 1, 1, 1, 1, 1, 1, 1, 1]
  Wf_v: [20, 20, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2]

  # nominal trajecotry control points
  ctrl_pts: 
  - [0.53, 0.53, 0.53, 0.53, 0.53]    # z-pos
  - [0, .75, 1.5, 2.25, 3.0]    # x-pos
  - [0,    0.,    0.,  0.,   0]    # theta
  - [0,    0,    0,    0,    0]    # hip_r
  - [0,    0,    0,    0,    0]    # knee_r
  - [0,    0,    0,    0,    0]    # ankle_r
  - [0,    0,    0,    0,    0]    # foot_r
  - [0,    0,    0,    0,    0]    # hip_l  
  - [0,    0,    0,    0,    0]    # knee_l
  - [0,    0,    0,    0,    0]    # ankle_l
  - [0,    0,    0,    0,    0]    # foot_l

