
squat:
  # Path to URDF
  model_file: "./urdf/harpy_planar.urdf"

  # configuration space
  # z-pos, x-pos, [0-1]
  # theta,        [2]
  # hip_r, knee_r, ankle_r, foot_r [3-6]
  # hip_l, knee_l, ankle_l, foot_l [7-10]

  # MPC parameters
  T: 3.5   # total time horizon
  dt: 0.05 # time step

  # Cost Parameters
  w_4bar_q: 200
  w_4bar_v: 20
  Wq:   [200, 30, 1, 70, 70, 70, 70, 70, 70, 70, 70]   
  Wv:   [20, 30, 1, 30, 30, 30, 30, 30, 30, 30, 30]
  R:    [1_000_000, 1_000_000, 1_000_000, 1, 1, 0, 1, 1, 1, 0, 1]
  Wf_q: [900, 200, 10, 100, 100, 100, 100, 100, 100, 100, 100]   
  Wf_v: [500, 200, 10, 100, 100, 100, 100, 100, 100, 100, 100]   

  # nominal trajecotry control points
  ctrl_pts: 
  # - [0.53, 0.53, 0.53, 0.53, 0.53] # z-pos
  # - [0.53, 0.53, 0.53, 0.53, 0.53] # x-pos
  # - [0,    0,    0,    0,    0]    # theta
  - [ 0.43,  0.4,  0.7,  0.4,  0.43]
  - [ 0.,    0.,    0.2,  1.0,  1.0]
  - [ 0,    0.,    0.,  0.,   0.1]
  - [0,    0,    0,    0,    0]    # hip_r
  - [0,    0,    0,    0,    0]    # knee_r
  - [0,    0,    0,    0,    0]    # ankle_r
  - [0,    0,    0,    0,    0]    # foot_r
  - [0,    0,    0,    0,    0]    # hip_l  
  - [0,    0,    0,    0,    0]    # knee_l
  - [0,    0,    0,    0,    0]    # ankle_l
  - [0,    0,    0,    0,    0]    # foot_l


walk:
  # Path to URDF
  model_file: "./urdf/harpy_planar.urdf"

  # configuration space
  # z-pos, x-pos, [0-1]
  # theta,        [2]
  # hip_r, knee_r, ankle_r, foot_r [3-6]
  # hip_l, knee_l, ankle_l, foot_l [7-10]

  # MPC parameters
  T: 3.5   # total time horizon
  dt: 0.05 # time step

  # Cost Parameters
  w_4bar_q: 0
  w_4bar_v: 0
  Wq:   [200, 30, 1, 70, 70, 70, 70, 70, 70, 70, 70]   
  Wv:   [20, 30, 1, 30, 30, 30, 30, 30, 30, 30, 30]
  R:    [1_000_000, 1_000_000, 1_000_000, 1, 1, 0, 1, 1, 1, 0, 1]
  Wf_q: [900, 200, 10, 100, 100, 100, 100, 100, 100, 100, 100]   
  Wf_v: [500, 200, 10, 100, 100, 100, 100, 100, 100, 100, 100]   

  # nominal trajecotry control points
  ctrl_pts: 
  # - [0.53, 0.53, 0.53, 0.53, 0.53] # z-pos
  # - [0.53, 0.53, 0.53, 0.53, 0.53] # x-pos
  # - [0,    0,    0,    0,    0]    # theta
  - [ 0.43,  0.4,  0.7,  0.4,  0.43]
  - [ 0.,    0.,    0.2,  1.0,  1.0]
  - [ 0,    0.,    0.,  0.,   0.1]
  - [0,    0,    0,    0,    0]    # hip_r
  - [0,    0,    0,    0,    0]    # knee_r
  - [0,    0,    0,    0,    0]    # ankle_r
  - [0,    0,    0,    0,    0]    # foot_r
  - [0,    0,    0,    0,    0]    # hip_l  
  - [0,    0,    0,    0,    0]    # knee_l
  - [0,    0,    0,    0,    0]    # ankle_l
  - [0,    0,    0,    0,    0]    # foot_l

